spring:
  application:
    name: E-Commerce-Backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db

springdoc:
  swagger-ui:
    path: /swagger-ui.html

razorpay:
  key:
    id: rzp_test_S6A07Fy7SeMGWS
    secret: ye6YrwsBgEvh8G4K4Syc5vO7
